# Generated by Django 5.0.3 on 2024-03-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.CharField(default="Extra", max_length=100),
        ),
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.TextField(default="description"),
        ),
        migrations.AddField(
            model_name="products",
            name="dicount_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="products",
            name="title",
            field=models.CharField(default="title", max_length=200),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.CharField(default="image", max_length=300),
        ),
    ]
