# Generated by Django 5.0.2 on 2024-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_products_category_products_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.TextField(max_length=1000)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.TextField(max_length=1000)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="dicount_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
