# Generated by Django 4.2.3 on 2024-04-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totals',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
