# Generated by Django 5.0.2 on 2024-04-02 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_orders_totals"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="totals",
            new_name="total",
        ),
    ]
